### ISSUE TITLE
Question: Moiety Sorted

### ISSUE THREAD

**Issue by galjos** [SimonEnsemble/PoreMatMod.jl#151]
Is there a possibility to keep the atom sorting from the `xyz-file` when using `moiety()` ? 

```
julia> moiety("glycine_res.xyz")
Crystal(C₂H₃NO, periodic = TTT):
    bounding_box      : [       1        0        0;
                         6.12323e-17        1        0;
                         6.12323e-17 6.12323e-17        1]u"Å"

    Atoms{Frac}(1, [:C], Frac([-3.0898692; -0.95823882; 0.0;;]))
    Atoms{Frac}(1, [:N], Frac([-2.4029152; -2.23405082; 0.0;;]))
    Atoms{Frac}(1, [:C], Frac([-2.0853462; 0.18518518; 0.0;;]))
    Atoms{Frac}(1, [:H], Frac([-1.4033551999999998; -2.26371682; 0.0;;]))
    Atoms{Frac}(1, [:H], Frac([-3.7147022; -0.88143582; -0.889823;;]))
    Atoms{Frac}(1, [:H], Frac([-3.7147022; -0.88143582; 0.889823;;]))
    Atoms{Frac}(1, [:O], Frac([-0.8513402; -0.06139382; 0.0;;]))


shell> cat glycine_res.xyz
7

 N                 -2.40291520   -2.23405082    0.00000000
 H                 -1.40335520   -2.26371682    0.00000000
 C                 -3.08986920   -0.95823882    0.00000000
 C                 -2.08534620    0.18518518    0.00000000
 H                 -3.71470220   -0.88143582   -0.88982300
 H                 -3.71470220   -0.88143582    0.88982300
 O                 -0.85134020   -0.06139382    0.00000000

```

**Comment by eahenle** [comment]
> we should put this in the doc string as a warning?
absolutely
> is the reason for doing this, for some down-stream efficiency during the search?
yes
> would the code break if we were to provide a keyword argument sort_atoms=true?
let's see

The atoms are sorted by node degree so that when the structure matching algorithm iterates through them, we get the best pruning of the search tree.  We should mention this caveat in the docstring, for sure.  I'll try out the idea of conditionally skipping that re-ordering.

@galjos an immediate workaround could be to import the XYZ data via `moiety` and then save a new version of the data file `glycine_res_pmm.xyz`.  Subsequent re-loading of the data file will preserve the order.  If all that matters is correspondence between `PoreMatMod`'s indexing and the source file's, this solves the problem without sacrificing any search speed.
![image](https://github.com/SimonEnsemble/PoreMatMod.jl/assets/16201240/b75a0b10-c5a3-4c72-9362-ae987887833f)

**Comment by galjos** [comment]
Thanks a lot, @eahenle and @SimonEnsemble .
